# Generated by Django 4.2.27 on 2026-01-20 21:35

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import sports_trainings_and_tournaments_in_mg.web.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, validators=[sports_trainings_and_tournaments_in_mg.web.validators.contains_only_letters_validator, django.core.validators.MinLengthValidator(2)])),
                ('prize', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(2)])),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, validators=[sports_trainings_and_tournaments_in_mg.web.validators.contains_only_letters_validator, django.core.validators.MinLengthValidator(2)])),
                ('participators', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ActivityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.activity')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('football', 'football'), ('basketball', 'basketball'), ('volleyball', 'volleyball'), ('table tennis', 'table tennis'), ('running', 'running'), ('badminton', 'badminton')], max_length=12, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, validators=[sports_trainings_and_tournaments_in_mg.web.validators.contains_only_letters_validator, django.core.validators.MinLengthValidator(2)])),
                ('is_full', models.BooleanField(default=False)),
                ('date', models.DateField()),
                ('achievements', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.achievement')),
                ('activities', models.ManyToManyField(related_name='events', through='web.ActivityEvent', to='web.activity')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('student', 'student'), ('teacher', 'teacher')], max_length=7)),
                ('grade', models.CharField(blank=True, max_length=4, null=True, validators=[django.core.validators.MinLengthValidator(2)])),
            ],
            options={
                'permissions': (('can_approve_requests', 'Can approve or reject participation requests'), ('', '')),
            },
        ),
        migrations.CreateModel(
            name='ProfileEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event', to='web.event')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='web.profile')),
            ],
            options={
                'unique_together': {('profile', 'event')},
            },
        ),
        migrations.CreateModel(
            name='ProfileCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.category')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.profile')),
            ],
            options={
                'unique_together': {('profile', 'category')},
            },
        ),
        migrations.CreateModel(
            name='ProfileAchievements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achievements', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.achievement')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.profile')),
            ],
            options={
                'unique_together': {('profile', 'achievements')},
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='categories',
            field=models.ManyToManyField(related_name='profiles', through='web.ProfileCategory', to='web.category'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='PermissionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('rejected', 'rejected')], default='pending', max_length=8)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_requests', to='web.event')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='students',
            field=models.ManyToManyField(related_name='events', through='web.ProfileEvent', to='web.profile'),
        ),
        migrations.AddField(
            model_name='activityevent',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.event'),
        ),
        migrations.AddField(
            model_name='activity',
            name='category',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='web.category'),
        ),
        migrations.AddField(
            model_name='achievement',
            name='students',
            field=models.ManyToManyField(related_name='achievements', through='web.ProfileAchievements', to='web.profile'),
        ),
    ]
