# Generated by Django 4.2.27 on 2026-01-22 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_alter_achievement_name_alter_activity_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='achievements',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.achievement'),
        ),
    ]
