# Generated by Django 4.2.27 on 2026-02-03 13:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_alter_event_achievements'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.PositiveIntegerField(blank=True, choices=[(5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)], null=True)),
                ('class_letter', models.CharField(blank=True, choices=[('А', 'А'), ('Б', 'Б'), ('В', 'В'), ('Г', 'Г'), ('Д', 'Д'), ('Е', 'Е'), ('Ж', 'Ж'), ('З', 'З')], max_length=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GradeTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.grade')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_teams_per_match', models.PositiveIntegerField(default=2)),
                ('start_time', models.DateTimeField()),
                ('duration', models.PositiveIntegerField()),
                ('result', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('numbers_of_players', models.PositiveIntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='web.category')),
                ('grades', models.ManyToManyField(related_name='teams', through='web.GradeTeam', to='web.grade')),
            ],
        ),
        migrations.RenameModel(
            old_name='ProfileAchievements',
            new_name='ProfileAchievement',
        ),
        migrations.RemoveField(
            model_name='achievement',
            name='students',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='participators',
        ),
        migrations.RemoveField(
            model_name='event',
            name='achievements',
        ),
        migrations.RemoveField(
            model_name='event',
            name='is_full',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='grade',
        ),
        migrations.AddField(
            model_name='activity',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='achievements',
            field=models.ManyToManyField(related_name='profiles', through='web.ProfileAchievement', to='web.achievement'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='web.category'),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.CreateModel(
            name='TeamProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.profile')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.team')),
            ],
            options={
                'unique_together': {('profile', 'team')},
            },
        ),
        migrations.CreateModel(
            name='TeamMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.match')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.team')),
            ],
            options={
                'unique_together': {('team', 'match')},
            },
        ),
        migrations.AddField(
            model_name='team',
            name='students',
            field=models.ManyToManyField(related_name='teams', through='web.TeamProfile', to='web.profile'),
        ),
        migrations.AddField(
            model_name='match',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matches', to='web.activity'),
        ),
        migrations.AddField(
            model_name='match',
            name='teams',
            field=models.ManyToManyField(related_name='matches', through='web.TeamMatch', to='web.team'),
        ),
        migrations.AddField(
            model_name='gradeteam',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.team'),
        ),
        migrations.CreateModel(
            name='GradeActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.activity')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.grade')),
            ],
        ),
        migrations.AddField(
            model_name='grade',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='grade', to='web.profile'),
        ),
        migrations.AddField(
            model_name='activity',
            name='grades',
            field=models.ManyToManyField(related_name='activities', through='web.GradeActivity', to='web.grade'),
        ),
        migrations.AlterUniqueTogether(
            name='gradeteam',
            unique_together={('grade', 'team')},
        ),
        migrations.AlterUniqueTogether(
            name='grade',
            unique_together={('grade', 'class_letter')},
        ),
    ]
