# Generated by Django 4.2.27 on 2026-02-03 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_grade_gradeteam_match_team_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='grades',
            field=models.ManyToManyField(blank=True, related_name='activities', through='web.GradeActivity', to='web.grade'),
        ),
        migrations.AlterField(
            model_name='event',
            name='activities',
            field=models.ManyToManyField(blank=True, related_name='events', through='web.ActivityEvent', to='web.activity'),
        ),
        migrations.AlterField(
            model_name='event',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='events', through='web.ProfileEvent', to='web.profile'),
        ),
        migrations.AlterField(
            model_name='match',
            name='max_teams_per_match',
            field=models.PositiveIntegerField(blank=True, default=2),
        ),
        migrations.AlterField(
            model_name='match',
            name='teams',
            field=models.ManyToManyField(blank=True, related_name='matches', through='web.TeamMatch', to='web.team'),
        ),
        migrations.AlterField(
            model_name='team',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='teams', through='web.TeamProfile', to='web.profile'),
        ),
    ]
