# Generated by Django 4.2.27 on 2026-02-04 14:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0006_alter_activity_grades_alter_event_activities_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamPermissionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('rejected', 'rejected')], default='pending', max_length=8)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_requests', to='web.event')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='team',
            name='status',
            field=models.CharField(choices=[('editing', 'editing'), ('locked', 'locked')], default='editing', max_length=7),
        ),
        migrations.DeleteModel(
            name='PermissionRequest',
        ),
        migrations.AddField(
            model_name='teampermissionrequest',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='web.team'),
        ),
        migrations.AlterUniqueTogether(
            name='teampermissionrequest',
            unique_together={('team', 'student')},
        ),
    ]
