# Generated by Django 4.2.27 on 2026-02-12 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_alter_teampermissionrequest_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='activities',
            field=models.ManyToManyField(related_name='events', through='web.ActivityEvent', to='web.activity'),
        ),
    ]
