# Generated by Django 4.2.27 on 2026-02-16 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_alter_event_activities'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='label',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
