# Generated by Django 4.2.27 on 2026-02-23 20:20

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_match_label'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='TeamAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameField(
            model_name='achievement',
            old_name='prize',
            new_name='award',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='achievements',
        ),
        migrations.AddField(
            model_name='achievement',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True, validators=[django.core.validators.MinLengthValidator(5)]),
        ),
        migrations.DeleteModel(
            name='ProfileAchievement',
        ),
        migrations.AddField(
            model_name='teamachievement',
            name='achievement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.achievement'),
        ),
        migrations.AddField(
            model_name='teamachievement',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.team'),
        ),
        migrations.AddField(
            model_name='eventachievement',
            name='achievement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.achievement'),
        ),
        migrations.AddField(
            model_name='eventachievement',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.event'),
        ),
        migrations.AddField(
            model_name='event',
            name='achievements',
            field=models.ManyToManyField(related_name='events', through='web.EventAchievement', to='web.achievement'),
        ),
        migrations.AddField(
            model_name='team',
            name='achievements',
            field=models.ManyToManyField(related_name='teams', through='web.TeamAchievement', to='web.achievement'),
        ),
        migrations.AlterUniqueTogether(
            name='teamachievement',
            unique_together={('team', 'achievement')},
        ),
    ]
