# Generated by Django 4.2.27 on 2026-03-04 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_eventachievement_teamachievement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='grades',
            field=models.ManyToManyField(blank=True, related_name='teams', through='web.GradeTeam', to='web.grade'),
        ),
    ]
