# Generated by Django 4.2.27 on 2026-03-06 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_alter_team_grades'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='absence_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_banned_from_participation',
            field=models.BooleanField(default=False),
        ),
    ]
