# Generated by Django 4.2.27 on 2026-03-09 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_profile_absence_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='event',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='match',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='team',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
