# Generated by Django 4.2.27 on 2026-03-14 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0016_alter_profile_options_profile_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='numbers_of_players',
            new_name='number_of_players',
        ),
    ]
