# Generated by Django 4.2.27 on 2026-03-14 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0017_rename_numbers_of_players_team_number_of_players'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='eventachievement',
            unique_together={('event', 'achievement')},
        ),
    ]
