# Generated by Django 4.2.27 on 2026-03-15 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0018_alter_eventachievement_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='status',
        ),
        migrations.AddField(
            model_name='teammatch',
            name='status',
            field=models.CharField(choices=[('editing', 'editing'), ('locked', 'locked')], default='editing', max_length=7),
        ),
    ]
