# Generated by Django 4.2.27 on 2026-03-16 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0019_remove_team_status_teammatch_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='teampermissionrequest',
            name='team_match',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='web.teammatch'),
            preserve_default=False,
        ),
    ]
