# Generated by Django 4.2.27 on 2026-03-16 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0020_teampermissionrequest_team_match'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammatch',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_matches', to='web.match'),
        ),
    ]
