# Generated by Django 4.2.27 on 2026-03-20 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0021_alter_teammatch_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='last_promoted_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
