# Generated by Django 4.2.27 on 2026-03-23 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0022_grade_last_promoted_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMatchProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.profile')),
                ('team_match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.teammatch')),
            ],
            options={
                'unique_together': {('profile', 'team_match')},
            },
        ),
        migrations.RemoveField(
            model_name='team',
            name='students',
        ),
        migrations.DeleteModel(
            name='TeamProfile',
        ),
        migrations.AddField(
            model_name='teammatch',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='student_team_matches', through='web.TeamMatchProfile', to='web.profile'),
        ),
    ]
