# Generated by Django 4.2.27 on 2026-03-23 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0023_teammatchprofile_remove_team_students_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(choices=[('football', 'футбол'), ('basketball', 'баскетбол'), ('volleyball', 'волейбол'), ('table tennis', 'тенис на маса'), ('running', 'бягане'), ('badminton', 'бадминтон')], max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='teammatch',
            name='status',
            field=models.CharField(choices=[('editing', 'редактира се'), ('locked', 'заключен')], default='editing', max_length=7),
        ),
        migrations.AlterField(
            model_name='teampermissionrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'чакащ'), ('approved', 'одобрен'), ('rejected', 'отхвърлен')], default='pending', max_length=8),
        ),
    ]
