# Generated by Django 4.2.27 on 2026-03-23 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0024_alter_category_category_alter_teammatch_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileevent',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='web.event'),
        ),
        migrations.AlterField(
            model_name='profileevent',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='web.profile'),
        ),
    ]
