# Generated by Django 4.2.27 on 2026-03-23 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0025_alter_profileevent_event_alter_profileevent_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(choices=[('football', 'футбол'), ('volleyball', 'волейбол'), ('basketball', 'баскетбол'), ('table tennis', 'тенис на маса'), ('running', 'бягане'), ('badminton', 'бадминтон')], max_length=12, unique=True),
        ),
    ]
